#!/bin/env bash

# route settings
iptables -t nat -nL | grep 'MASQUERADE' | grep '172.17.0.0/24' | grep '192.168.0.0/16'
if [[ $? -ne 0 ]]; then
    iptables -t nat -A POSTROUTING -s 172.17.0.0/24 -d 192.168.0.0/16 -j MASQUERADE
fi
iptables -t nat -nL | grep 'MASQUERADE' | grep '172.17.1.0/24' | grep '192.168.0.0/16'
if [[ $? -ne 0 ]]; then
    iptables -t nat -A POSTROUTING -s 172.17.1.0/24 -d 192.168.0.0/16 -j MASQUERADE
fi

# vpn
SERVER=
AUTHGROUP=
USERNAME=
PASSWORD=
rm /tmp/vpn.pin
gnutls-cli --print-cert ${SERVER} < /dev/null | grep pin-sha256: > /tmp/vpn.pin
echo ${PASSWORD} | openconnect --authgroup=${AUTHGROUP} --user=${USERNAME} --passwd-on-stdin ${SERVER} --servercert $(cat /tmp/vpn.pin) --force-dpd=604800

