#!/bin/bash


SKIM_DEFAULT_OPTIONS="--reverse --height 40% --no-mouse --preview-window right:70% --bind '?:toggle-preview,ctrl-o:execute-silent(xdg-open {})'"
SKIM_CTRL_T_OPTS="--preview 'bat --color always {}'"

if [[ $- =~ i ]]; then

__skim_file_widget__() {
  local selected="$(
    local cmd="fd 2>/dev/null"
    eval "$cmd" | SKIM_DEFAULT_OPTIONS="$SKIM_DEFAULT_OPTIONS $SKIM_CTRL_T_OPTS" sk -m "$@" | while read -r item; do
      printf '%q ' "$item"
    done
    echo)"
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}

__skim_file_content_widget__() {
  local selected="$(
    sk --ansi -i -c 'rg --color=always --line-number "{}"' | while read -r item; do
      printf '%q ' "$item"
    done
    echo)"
  if [[ -n "$selected" ]]; then
    echo vim +$(echo $selected | cut -d: -f 2) $(echo $selected | cut -d: -f 1)
  fi
}

__skim_cd__() {
  local cmd dir
  cmd="fd --type d 2>/dev/null"
  dir=$(eval "$cmd" | SKIM_DEFAULT_OPTIONS="$SKIM_DEFAULT_OPTIONS $SKIM_ALT_C_OPTS" sk --no-multi) && printf 'cd %q' "$dir"
}

__skim_history__() {
  local output
  output=$(
    builtin fc -lnr -2147483648 |
      last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |
      SKIM_DEFAULT_OPTIONS="$SKIM_DEFAULT_OPTIONS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $SKIM_CTRL_R_OPTS --no-multi --read0" sk --query "$READLINE_LINE"
  ) || return
  READLINE_LINE=${output#*$'\t'}
  if [ -z "$READLINE_POINT" ]; then
    echo "$READLINE_LINE"
  else
    READLINE_POINT=0x7fffffff
  fi
}

# Required to refresh the prompt after skim
bind -m emacs-standard '"\er": redraw-current-line'

bind -m vi-command '"\C-z": emacs-editing-mode'
bind -m vi-insert '"\C-z": emacs-editing-mode'
bind -m emacs-standard '"\C-z": vi-editing-mode'

# CTRL-T - Paste the selected file path into the command line
bind -m emacs-standard -x '"\C-t": __skim_file_widget__'
bind -m vi-command -x '"\C-t": __skim_file_widget__'
bind -m vi-insert -x '"\C-t": __skim_file_widget__'

# ALT-T - ???????
bind -m emacs-standard '"\et": " \C-b\C-k \C-u`__skim_file_content_widget__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\et": "\C-z\et\C-z"'
bind -m vi-insert '"\et": "\C-z\et\C-z"'

# CTRL-R - Paste the selected command from history into the command line
bind -m emacs-standard -x '"\C-r": __skim_history__'
bind -m vi-command -x '"\C-r": __skim_history__'
bind -m vi-insert -x '"\C-r": __skim_history__'

# ALT-C - cd into the selected directory
bind -m emacs-standard '"\ec": " \C-b\C-k \C-u`__skim_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\ec": "\C-z\ec\C-z"'
bind -m vi-insert '"\ec": "\C-z\ec\C-z"'

fi
